const brands: string[] = [
	'Ferrari',
	'McLaren',
	'Porsche',
	'Mercedes',
	'Lamborghini',
	'AstonMartin',
	'Audi',
	'BMW',
	'Nissan',
	'Toyota',
	'Ford',
	'Chevrolet',
	'Jaguar',
	'Land Rover',
	'Subaru',
	'Volkswagen',
	'Hyundai',
	'Kia',
	'Mazda',
	'Buick',
];

const models: string[] = [
	'F1-75',
	'SF90 Stradale',
	'488 Pista',
	'LaFerrari',
	'GTC4Lusso',
	'812 Superfast',
	'Portofino M',
	'F8 Tributo',
	'458 Italia',
	'California T',
	'MP4/4',
	'720S GT3X',
	'P1 GTR',
	'765LT',
	'600LT',
	'570S',
	'650S',
	'Artura',
	'540C',
	'McLaren Sabre',
	'911 RSR',
	'935',
	'919 Hybrid',
	'718 Cayman GT4',
	'911 Turbo S',
	'911 GT3',
	'918 Spyder',
	'Panamera Turbo',
	'Macan GTS',
	'Cayenne Turbo',
	'AMG GT3',
	'F1 W11',
	'CLK GTR',
	'AMG GT Black Series',
	'SLS AMG',
	'AMG C63 DTM',
	'Evo GT4',
	'SLR McLaren',
	'AMG A45',
	'AMG GLE 63',
	'Huracán GT3 EVO',
	'SC18 Alston',
	'Essenza SCV12',
	'Aventador SVJ',
	'Huracán STO',
	'Urus',
	'Aventador S',
	'Huracán Performante',
	'Gallardo Superleggera',
	'Reventón',
	'Vantage GT3',
	'DBR9',
	'Vulcan',
	'DB11 AMR',
	'Vantage AMR',
	'DBX',
	'Rapide AMR',
	'Vanquish S',
	'DBS Superleggera',
	'Vantage Roadster',
	'R8 LMS',
	'RS 5 DTM',
	'Sport Quattro S1',
	'R8 Spyder',
	'RS Q8',
	'A6 Avant',
	'S5 Coupe',
	'A7 Sportback',
	'Q3 Sportback',
	'TT RS',
	'M4 GT3',
	'M8 GTE',
	'Z4 GT3',
	'M2 Competition',
	'M5 CS',
	'X6 M',
	'i8 Roadster',
	'7 Series',
	'3 Series Touring',
	'8 Series Gran Coupe',
	'GT-R NISMO GT3',
	'370Z Nismo',
	'R390 GT1',
	'GT-R R35',
	'350Z',
	'Altima Coupe',
	'370Z Roadster',
	'GT-R LM',
	'Juke Nismo',
	'GT-R R34',
	'TS050 Hybrid',
	'GR010 Hybrid',
	'Supra GT4',
	'GR Yaris',
	'Camry XSE',
	'Land Cruiser 300',
	'Hilux',
	'Corolla Hatchback',
	'C-HR',
	'Tacoma TRD Pro',
];

const getRandomElement = (arr: string[]) =>
	arr[Math.floor(Math.random() * arr.length)];

const generateRandomCars = () => {
	const randomCars = [];
	for (let i = 0; i < 100; i++) {
		const brand = getRandomElement(brands);
		const model = getRandomElement(models);
		randomCars.push({
			name: `${brand} ${model}`,
			color: `#${(0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6)}`,
		});
	}

	return randomCars;
};

export default generateRandomCars;
